### ISSUE TITLE
`copy` has to cope with self-copying

### ISSUE THREAD

**Issue by dangelog** [KDAB/KDAlgorithms#10]
Can I concatenate a vector to itself using `copy`?

```
std::vector<int> v{1, 2, 3};
KDAlgorithms::copy(v, v); // duplicate it
```

The current answer is "maybe", which is a bad answer. If you want this to be a precondition, it should be documented (and assert()ed, e.g. `assert(&input != &output)`).

**Comment by jesperkdab** [comment]
Was fixed back in November.
