### ISSUE TITLE
Should `min_element` and `max_element` be called `min_value` / `max_value`?

### ISSUE THREAD

**Issue by dangelog** [KDAB/KDAlgorithms#11]
`max_element` is used to retrieve to the position (as in, an iterator) of the maximum element. But the implementation here returns the value (wrapped in an `optional`), not the iterator pointing to it. Should these `_element` functions be renamed to something like `max_value`?

**Comment by dfaure-kdab** [comment]
I agree, I was initially a bit confused about what these would do.

But maybe SC has to be kept at this point?
