### ISSUE TITLE
work with std::range::subrange

### ISSUE THREAD

**Issue by hmoffatt** [KDAB/KDAlgorithms#68]
Possibly related to #4 is it possible to make the algorithms work with subranges?

Occasionally I need to use an algorithm on a subset of a container. I like using kdalgorithms rather than STL because kdalgorithms::transformed for example returns the new container rather than requiring it to be declared in advance.

I tried this; all_of compiles, but transformed does not, complaining about missing value_type in the subrange (in MSVC 2022):

```
	std::vector<int> test;
	auto x = kdalgorithms::all_of(std::ranges::subrange(test.cbegin(), test.cend()),
		[](const int i) -> bool { return i == 0; });

	auto y = kdalgorithms::transformed<std::vector<int>>(std::ranges::subrange(test.cbegin(), test.cend()),
		[](const int i) -> int { return i + 1; });
```

**Comment by jesperkdab** [comment]
Thanks for the feedback. I looked shortly at subrange, and indeed I see no value_type in there, which is all over the place for kdalgorithms. I've very little insight into how std::ranges works, so I'm afraid I realistically wouldn't get to fix this.

I'll leave it open in case someone else knows of a way around this (without a huge rewrite to KDAlgorithms)

Cheers
Jesper.

**Comment by hmoffatt** [comment]
It looks like there is std::ranges::range_value_t<> for this.. I don't know if this fits in with your ValueTypeHelper though. 
https://stackoverflow.com/questions/74496713/how-to-get-the-type-of-the-values-in-a-c20-stdranges-range

**Comment by jesperkdab** [comment]
Please try https://github.com/KDAB/KDAlgorithms/pull/70 which at least works with your example now.

**Comment by hmoffatt** [comment]
Looks good! I tried a few things with QVector and std::vector and it worked as expected.

I tried working on a subrange of std::map and didn't have much luck, though clang++ 14 couldn't even compile the non-kdalgorithms code (g++ 12 did), so I'm not sure if the code makes any sense.

```
        std::map<int, QString> test;
        test[0] = "hi";
        test[1] = "there";
        
        for (auto it = test.begin(); it != test.end(); it++)
            qDebug() << *it;

        auto sub = std::ranges::subrange(test.cbegin(), test.cend());
        for (auto [k, v] : sub)
            qDebug() << k << v;

        qDebug() << kdalgorithms::transformed<std::vector<QString>>(sub,
            [](const auto& v) -> QString { return v.second; });
```

My only interest is in a subrange of a vector currently anyway. Thanks for working on this.

**Comment by jesperkdab** [comment]
Implemented.
