### ISSUE TITLE
Release KDAlgorithms 1.4

### ISSUE THREAD

**Issue by iamsergio** [KDAB/KDAlgorithms#78]
Let me know if I can release 1.3 as it includes "make install" and can now be consumed via homebrew package

**Comment by hmoffatt** [comment]
That'd be great, I consume kdalgorithms via vcpkg and I'd love to have the latest changes in there.

**Comment by iamsergio** [comment]
@jesperkdab assigned to you, please release whenever you're ready

**Comment by hmoffatt** [comment]
> See also [microsoft/vcpkg#42624](https://github.com/microsoft/vcpkg/pull/42624)

Great, saved me the trouble!
